stew-project/stew/urls.py
from django.contrib import admin
from django.urls import path
from main import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #STEW
    path('', views.home, name='home'),
    path('courses/', views.courses, name='courses'),
    path('createcourse/', views.createcourse, name='createcourse'),
    path('joincourse/', views.joincourse, name='joincourse'),
    path('course/<int:course_pk>/', views.coursehome, name='coursehome'),
    
    path('addteachingassistant/<int:course_pk>/', views.addteachingassistant, name='addteachingassistant'),
    path('removeteachingassistant/<int:course_pk>/', views.removeteachingassistant, name='removeteachingassistant'),
    path('editcourseteamrules/<int:course_pk>/', views.editcourseteamrules, name='editcourseteamrules'),
    
    #Teams
    path('jointeam/', views.jointeam, name='jointeam'),
    path('createteam/<int:course_pk>/<int:team_pk>/', views.createteam, name='createteam'),
    path('team/<int:team_pk>/', views.teamhome, name='teamhome'),
    
    #Meetings
    path('addmeeting/<int:course_pk>/<int:team_pk>/', views.addmeeting, name='addmeeting'),
    path('meetinginfo/<int:meeting_pk>/', views.meetinginfo, name='meetinginfo'),
    path('editmeeting/<int:meeting_pk>/', views.editmeeting, name='editmeeting'),
    
    #Tasks
    path('assigntask/<int:course_pk>/<int:team_pk>/', views.assigntask, name='assigntask'),
    path('viewtask/<int:task_pk>/', views.viewtask, name='viewtask'),
    path('edittask/<int:task_pk>/', views.edittask, name='edittask'),
    path('downloadtaskattachment/<int:task_pk>/', views.downloadtaskattachment, name='downloadtaskattachment'),
    path('addtasksubmission/<int:task_pk>/', views.addtasksubmission, name='addtasksubmission'),
    path('viewtasksubmission/<int:submission_pk>/', views.viewsubmission, name='viewsubmission'),
    path('editsubmission/<int:submission_pk>/', views.editsubmission, name='editsubmission'),
    path('gradesubmission/<int:submission_pk>/', views.gradesubmission, name='gradesubmission'),
    path('downloadsubmissionattachment/<int:submission_pk>/', views.downloadsubmissionattachment, name='downloadsubmissionattachment'),
    path('downloadgradingattachment/<int:submission_pk>/', views.downloadgradingattachment, name='downloadgradingattachment'),
    
    path('commentsubmission/<int:submission_pk>/', views.commentsubmission, name='commentsubmission'),
    path('editcomment/<int:comment_pk>/', views.editcomment, name='editcomment'),
    path('downloadcommentattachment/<int:comment_pk>/', views.downloadcommentattachment, name='downloadcommentattachment'),
    
    #FAQs
    path('faq/', views.faq, name='faq'),
    
    #Account Management
    path('logout/', views.logoutaccount, name='logoutaccount'),
    path('login/', views.loginaccount, name='loginaccount'),
    path('signup/', views.signupaccount, name='signupaccount'),
    path('user/<int:user_pk>/', views.userprofile, name='userprofile'),
    
    path('edituser/<int:user_pk>/', views.edituserprofile, name='edituserprofile'),
    
    path('test/', views.test, name='test')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stew-project/main/models.py
from django.db import models
from django.utils import timezone
from users.models import CustomUser


# Create your models here.

class Course(models.Model):
    
    name = models.CharField(max_length=100)
    
    join_code = models.CharField(max_length=100, unique=True)
    
    instructor = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="taught_courses")
    
    students = models.ManyToManyField(CustomUser, verbose_name=("Students"), related_name="courses", through="Enrollment")
    
    students_can_make_teams = models.BooleanField(default=False)
    
class Enrollment(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="enrollment")
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="enrollment")
    enrolled_as_ta = models.BooleanField(default=False)
    
class Team(models.Model):
    name = models.CharField(max_length=100)
    
    join_code = models.CharField(max_length=100, unique=True)
    
    members = models.ManyToManyField(CustomUser, verbose_name=("Members"), blank=True, related_name="teams", through='Membership')
    
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="teams")
    
    parent_team = models.ForeignKey('self', on_delete=models.CASCADE, related_name="subteams", null=True, blank=True)
    
class Membership(models.Model):
    student = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="membership")
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="membership")
    
class Task(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=5000, blank=True)
    
    attached = models.FileField(upload_to='main/task_attachments/%Y%m%d', null=True, blank=True)
    
    due_date = models.DateTimeField("Due Date", default=timezone.now, null=True, blank=True)
    assigned_date = models.DateTimeField("Assigned", default=timezone.now)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="all_tasks")
    
    #This team is the parent team of the teams which would make a submission for the task
    #If null, then it is a course level task
    task_level = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="task_level", null=True)
    
    is_team_task = models.BooleanField(default=False)
    
class TaskSubmission(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name="task_submissions")
    
    description = models.TextField(max_length=5000, blank=True)
    
    attached = models.FileField(upload_to='main/task_submissions/%Y%m%d', null=True, blank=True)
    
    team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="submitted_tasks", null=True, blank=True)
    
    submitter = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="submitted_task")
    
    submission_time = models.DateTimeField("Submitted", default=timezone.now)
    
    grade = models.FloatField(null=True, blank=True)
    
    grading_comments = models.TextField(max_length=5000, blank=True)
    
    grading_attached = models.FileField(upload_to='main/task_grading/%Y%m%d', null=True, blank=True)
    
    grader = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="graded_tasks", null=True, blank=True)
    
    grade_visible = models.BooleanField(null=True, blank=True, default=True)
    
    is_graded = models.BooleanField(null=True, blank=True, default=False)
    
    
class Meeting(models.Model):
    link = models.URLField(max_length=300)
    memo = models.TextField(max_length=500, blank=True)
    meeting_time = models.DateTimeField("Meeting Time", default=timezone.now)
    is_complete = models.BooleanField(default=False)
    meeting_course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="meetings")
    meeting_team = models.ForeignKey(Team, on_delete=models.CASCADE, related_name="meetings", null=True, blank=True)
    meeting_host = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="hosted_meetings")
    
class SubmissionComment(models.Model):
    submission = models.ForeignKey(TaskSubmission, on_delete=models.CASCADE, related_name="submission_comments")
    commenter = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name="comments")
    posted = models.DateTimeField("Posted", default=timezone.now)
    modified = models.DateTimeField("Modified", default=timezone.now)
    content = models.TextField(max_length=5000, blank=True)
    visible = models.BooleanField(null=True, blank=True, default=True)
    
    attached = models.FileField(upload_to='main/task_comments/%Y%m%d', null=True, blank=True)

stew-project/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.utils.translation import gettext_lazy as _

# Create your models here.

class CustomUserManager(BaseUserManager):
    
    def create_user(self, username, password, email, first_name, last_name, **otherfields):
        if not email:
            raise ValueError(_('You must provide an email address'))
        if not first_name:
            raise ValueError(_('You must provide your first name'))
        if not last_name:
            raise ValueError(_('You must provide your last name'))
        
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, first_name=first_name, last_name=last_name, **otherfields)
        user.set_password(password)
        user.save()
        return user
    
    def create_superuser(self, username, password, email, first_name, last_name, **otherfields):
        otherfields.setdefault('is_staff', True)
        otherfields.setdefault('is_superuser', True)
        otherfields.setdefault('is_active', True)
        otherfields.setdefault('status', 'admin')
        
        if otherfields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True'))
        if otherfields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True'))
        
        return self.create_user(username, password, email, first_name, last_name, **otherfields)
            

class CustomUser(AbstractBaseUser, PermissionsMixin):
    
    username = models.CharField(max_length=150, unique=True)
    USERNAME_FIELD = "username"
    
    email = models.EmailField(_("email address"))
    EMAIL_FIELD = "email"
    
    STATUS = (
        ('student', 'student'),
        ('teacher','teacher'),
        ('admin', 'admin'),
    )
    status = models.CharField(max_length=100, choices=STATUS, default='student')
    
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    
    description = models.TextField('Description', max_length=600, default='', blank=True)
    
    profile_picture = models.ImageField(upload_to='users/images', null=True, blank=True)
    
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']
    
    objects = CustomUserManager()
    
    def __str__(self):
        return self.username
    

stew-project/main/forms.py
from django.forms import ModelForm
from .models import Course, Team, Meeting, Task, TaskSubmission

class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = ['name', 'join_code']
        
class TeamForm(ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'join_code']
        
class MeetingForm(ModelForm):
    class Meta:
        model = Meeting
        fields = ['link', 'memo', 'meeting_time']
        
class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['name','description','attached','due_date','is_team_task']
        
class TestForm(ModelForm):
    class Meta:
        model = TaskSubmission
        fields = ['grade']

stew-project/main/templates/main/addmeeting.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">

<h1>Add Meeting</h1>

<hr>

<h2>{{ error }}</h2>

<form method="POST">
    {% csrf_token %}

    <p>
        <label for="id_link">Link:</label>
        <input type="url" name="link" maxlength="300" required="" id="id_link">
    </p>

    <p>
        <label for="id_memo">Memo:</label>
        <textarea name="memo" cols="40" rows="10" maxlength="500" id="id_memo"></textarea>
    </p>

    <p>
        <label for="id_meeting_time">Meeting Time:</label>
        <input type="datetime-local" name="meeting_time" value="{{time|date:'Y-m-d'}}T{{time|date:'H:i'}}" required="" id="id_meeting_time">
    </p>

<hr>

<button type="submit">Add</button>
</form>

</div>

<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        color: #333;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 600px;
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-top: 20px;
    }

    .task-submission-title {
        color: #007BFF;
    }

    .form-group {
        margin-bottom: 20px;
    }

    label {
        display: block;
        margin-bottom: 5px;
        color: #555;
    }

    input,
    textarea {
        width: 100%;
        padding: 8px;
        box-sizing: border-box;
        margin-top: 5px;
    }

    .save-button {
        background-color: #007BFF;
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .save-button:hover {
        background-color: #0056b3;
    }

    a {
        color: #007BFF;
        text-decoration: none;
    }

    a:hover {
        text-decoration: underline;
    }
</style>

{% endblock %}

stew-project/main/templates/main/assigntask.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">

<h1>Assign Task</h1>

<h2>{{ error }}</h2>

<hr>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <p>
        <label for="id_name">Name:</label>
        <input type="text" name="name" maxlength="100" required="" id="id_name">
    </p>

    <p>
        <label for="id_description">Description:</label>
        <textarea name="description" cols="40" rows="10" maxlength="5000" id="id_description"></textarea>
    </p>

    <hr>

    <p>
        <label for="id_attached">Attached:</label>
        <input type="file" name="attached" id="id_attached">
    </p>

    <hr>

    <p>
        <label for="id_due_date">Due Date:</label>
        <input type="datetime-local" name="due_date" value="{{time|date:'Y-m-d'}}T{{time|date:'H:i'}}" id="id_due_date">
    </p>

    <hr>

    <p>
        <label for="id_is_team_task">Is team task:</label>
        <input type="checkbox" name="is_team_task" id="id_is_team_task">
    </p>

    <hr>

    <button type="submit">Save</button>
</form>

</div>

<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        color: #333;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 600px;
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-top: 20px;
    }

    .task-submission-title {
        color: #007BFF;
    }

    .form-group {
        margin-bottom: 20px;
    }

    label {
        display: block;
        margin-bottom: 5px;
        color: #555;
    }

    input,
    textarea {
        width: 100%;
        padding: 8px;
        box-sizing: border-box;
        margin-top: 5px;
    }

    .save-button {
        background-color: #007BFF;
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .save-button:hover {
        background-color: #0056b3;
    }

    a {
        color: #007BFF;
        text-decoration: none;
    }

    a:hover {
        text-decoration: underline;
    }
</style>



{% endblock %}

stew-project/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>STEW</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            text-align: center;
        }

        .navbar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
            background-color: #f4f4f4;
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            margin-right: 10px;
            text-decoration: none;
            color: #333;
            background-color: #ddd;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .button:hover {
            background-color: #bbb;
        }

        .user-info {
            margin-bottom: 10px;
        }

        .auth-links {
            display: flex;
        }

    </style>
</head>

<body>

    {% if user.is_authenticated %}
    <div class="user-info">
        Logged in as {{ user.username }}
    </div>

    <nav class="navbar">
        <a href="{% url 'home' %}" class="button">Home</a>
        <a href="{% url 'courses' %}" class="button">Courses</a>

        <form action="{% url 'logoutaccount' %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="button">Logout</button>
        </form>
    </nav>

    {% else %}
    <nav class="navbar">
        <a href="{% url 'home' %}" class="button">Home</a>
        <div class="auth-links">
            <a href="{% url 'signupaccount' %}" class="button">Sign Up</a>
            <a href="{% url 'loginaccount' %}" class="button">Login</a>
        </div>
    </nav>
    {% endif %}

    <br>
    <br>

    {% block content %} {% endblock %}

</body>

</html>

stew-project/main/templates/main/editcomment.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">

<h1>Edit Comment</h1>

<h2>{{ error }}</h2>

<hr>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <p>
        <label for="id_content">Comment Content:</label>
        <textarea name="content" cols="40" rows="10" maxlength="5000" id="id_content">{{comment.content}}</textarea>   
    </p>
    
    <hr>

    <p>
        <label for="id_attached">New Attachment (Will Override Old Attachment):</label>
        <input type="file" name="attached" id="id_attached"> 
    </p>

    <hr>

    <p>
        <label for="id_visible">Comment Visible:</label>
        {% if comment.visible %}
            <input type="checkbox" name="visible" checked="True" id="id_visible">
        {% else %}
            <input type="checkbox" name="visible" id="id_visible">
        {% endif %}  

    </p>

    <hr>

    <button type="submit">Save</button>
</form>

</div>

<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        color: #333;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 600px;
        margin: 0 auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        margin-top: 20px;
    }

    .task-submission-title {
        color: #007BFF;
    }

    .form-group {
        margin-bottom: 20px;
    }

    label {
        display: block;
        margin-bottom: 5px;
        color: #555;
    }

    input,
    textarea {
        width: 100%;
        padding: 8px;
        box-sizing: border-box;
        margin-top: 5px;
    }

    .save-button {
        background-color: #007BFF;
        color: #fff;
        padding: 10px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    .save-button:hover {
        background-color: #0056b3;
    }

    a {
        color: #007BFF;
        text-decoration: none;
    }

    a:hover {
        text-decoration: underline;
    }
</style>



{% endblock %}

stew-project/main/templates/main/editcourseteamrules.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <h1 class="mb-4">Allow Students To Create Teams?</h1>

    <div class="alert alert-danger" role="alert">
        <h2>{{ error }}</h2>
    </div>

    <form method="POST">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_students_can_make_teams" class="form-check-label">Students are allowed to create teams:</label>

            <div class="form-check">
                {% if course.students_can_make_teams %}
                    <input type="checkbox" name="students_can_make_teams" checked="True" id="id_students_can_make_teams" class="form-check-input">
                {% else %}
                    <input type="checkbox" name="students_can_make_teams" id="id_students_can_make_teams" class="form-check-input">
                {% endif %}
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>

<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        text-align: center;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 600px;
        margin: 50px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1, h2 {
        color: #333;
    }

    .alert {
        margin-bottom: 20px;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-check-label {
        display: block;
        margin-bottom: 8px;
        color: #555;
    }

    .form-check-input {
        margin-top: 0;
    }

    button {
        background-color: #3498db;
        color: #fff;
        padding: 12px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #2980b9;
    }
</style>

{% endblock %}

stew-project/main/templates/main/gradesubmission.html
{% extends 'main/base.html' %}

{% block content %}

<div class="task-submission-container">
    <h1>Task Submission</h1>

    {% if submission.team %}
        <h2>Team: {{ submission.team.name }}</h2>
    {% endif %}

    <h3>Submitted by: {{ submission.submitter.first_name }} {{ submission.submitter.last_name }}</h3>

    <p>{{ submission.description }}</p>

    <br>

    {% if submission.attached %}
        <p>Attachment: <a href="{% url 'downloadsubmissionattachment' submission.id %}" download>{{ submission.attached.name }}</a></p>
    {% endif %}

    {% if submission.is_graded %}
        <div class="previous-grade-info">
            <p>Previous Grade: {{ submission.grade }}</p>
            <p>Previous Grader: {{ submission.grader.first_name }} {{ submission.grader.last_name }}</p>
            <p>Previous Comments: {{ submission.grading_comments }}</p>

            {% if submission.grading_attached %}
                <p>Previous Attachment: <a href="{% url 'downloadgradingattachment' submission.id %}" download>{{ submission.grading_attached.name }}</a></p>
            {% endif %}
        </div>
    {% endif %}

    <form method="POST" enctype="multipart/form-data" class="grading-form">
        {% csrf_token %}

        <div class="form-group">
            <label for="id_grade">Grade:</label>
            {% if submission.is_graded %}
                <input type="number" value="{{ submission.grade }}" name="grade" step="any" id="id_grade">
            {% else %}
                <input type="number" value="100.0" name="grade" step="any" id="id_grade">
            {% endif %}
        </div>

        <div class="form-group">
            <label for="id_grading_attached">Grading Attachment:</label>
            <input type="file" name="grading_attached" id="id_grading_attached">
        </div>

        <div class="form-group">
            <label for="id_grading_comments">Comments:</label>
            {% if submission.is_graded %}
                <textarea name="grading_comments" cols="40" rows="10" maxlength="5000" id="id_grading_comments">{{ submission.grading_comments }}</textarea>
            {% else %}
                <textarea name="grading_comments" cols="40" rows="10" maxlength="5000" id="id_grading_comments"></textarea>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="id_grade_visible">Grade Visible:</label>
            {% if submission.grade_visible %}
                <input type="checkbox" name="grade_visible" checked="True" id="id_grade_visible">
            {% else %}
                <input type="checkbox" name="grade_visible" id="id_grade_visible">
            {% endif %}
        </div>

        <button type="submit">Save</button>
    </form>
</div>

<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        text-align: center;
        margin: 0;
        padding: 0;
    }

    .task-submission-container {
        max-width: 800px;
        margin: 50px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1, h2, h3 {
        color: #333;
    }

    .form-group {
        margin-bottom: 20px;
    }

    label {
        display: block;
        margin-bottom: 8px;
        color: #555;
    }

    input, textarea, select {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button {
        background-color: #3498db;
        color: #fff;
        padding: 12px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #2980b9;
    }
</style>

{% endblock %}

stew-project/main/templates/main/signupaccount.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">

<h1> Signup </h1>

<h2>{{ error }}</h2>

<form method="POST">
    {% csrf_token %}

<p>
    <label for="id_username">Username:</label>
    <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="150" required id="id_username">
</p>
<p>
    <label for="id_email">Email:</label>
    <input type="email" name="email" autocapitalize="none" autocomplete="username" maxlength="150" required id="id_email">
</p>

<p>
    <label for="id_fname">First Name:</label>
    <input type="text" name="first_name" autocapitalize="none" autocomplete="username" maxlength="150" required id="id_fname">
</p>
<p>
    <label for="id_lname">Last Name:</label>
    <input type="text" name="last_name" autocapitalize="none" autocomplete="username" maxlength="150" required id="id_lname">
</p>

<p>
    <label for="id_password1">Password:</label>
    <input
        type="password"
        name="password1"
        autocomplete="current-password"
        maxlength="150"
        required
        pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}"
        oninvalid="this.setCustomValidity('Password must contain at least one digit, one lowercase letter, one uppercase letter, and be at least 8 characters long')"
        oninput="this.setCustomValidity('')"
        id="id_password1"
    >
</p>
<p>
    <label for="id_password2">Confirm Password:</label>
    <input type="password" name="password2" autocomplete="current-password" maxlength="150" required id="id_password2">
</p>
<p>
    <label for="id_my_role">I am a(n) </label>
    <select  name="my_role" required id="id_my_role">
        <option value="student" selected="selected">Student</option>
        <option value="instructor">Instructor</option>
    </select>
</p>

<button type="submit">Sign Up</button>
</form>

<p class="signup-link">
    <a href="{% url 'loginaccount' %}">Already have an account? Login.</a>
</p>

</div>

<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        text-align: center;
        margin: 0;
        padding: 0;
    }

    .container {
        max-width: 400px;
        margin: 50px auto;
        background-color: #fff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
        color: #333;
    }

    .error-message {
        color: #e74c3c;
        margin-bottom: 15px;
    }

    form {
        text-align: left;
    }

    .form-group {
        margin-bottom: 20px;
    }

    label {
        display: block;
        margin-bottom: 8px;
    }

    input {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button {
        background-color: #3498db;
        color: #fff;
        padding: 12px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    button:hover {
        background-color: #2980b9;
    }

    .signup-link {
        margin-top: 15px;
        font-size: 14px;
    }
</style>

{% endblock %}